.github/workflows/ci.yml
This PR adds the use of the `pytest-xdist` plugin to parallelize the `test_display.py` script (on a single runner; our tests are also parallelized across runners). The others are run as normal. This reduces the time required for `test_display` from ~30 minutes to ~20, while the others are unchanged.
=> use pytest-xdist to parallelize test_display (on a single runner)

.github/workflows/ci.yml, .github/workflows/treebeard.yml
The scheduled runs over the weekend failed while creating the environment with a strange pip error, the one seen [here](https://stackoverflow.com/questions/67273590/pip-21-1-cant-import-invalidschemecombination). As linked in that post, it's actually a [caching issue](https://github.com/pypa/pip/issues/9880), and so making sure not to cache pip solves the issue.
=> hotfix for weird caching issue

.github/workflows/treebeard.yml
Quick fix for failing treebeard job, adding `pip install chardet`
=> Tutorial fix

.github/workflows/ci.yml, .github/workflows/treebeard.yml
following Dylan's advice to remove the cache step (and replace it with caching from the `setup-python` action) in order to fix the failing python 3.7 tests. based on the error we were getting, he thought it likely that it was caused by an old version of `setuptools` and that the path list in our cache step looked questionable.
=> Fix failing python 3.7 tests

.gitignore, docs/index.rst, docs/reproducibility.rst, tests/test_metric.py, tests/test_models.py, tests/utils.py
This should fix #165. I added a version of the PS texture metamer synthesis file to compare against for v1.12.0 and above. Turns out that this change only affects the CPU, not GPU. Also made it so we test against the right version, based on torch version.
Also adds a small reprodubility page to the docs before merging (#144 )
=> Torch 1.12 fix

.github/workflows/ci.yml, jenkins/Dockerfile, setup.py
Small changes were necessary to make the install for the GPU-tests on jenkins have the same flags as for the CPU tests on Github actions.
This was a problem because the cached dependencies used in the GPU tests were getting out of sync (the matplotlib version required a newer numpy version, in #177 ), which the `--upgrade` flag should fix. (Note that we install the requirements using `requirements.txt` in the Dockerfile, which means they'll all get cached. The actions of the Jenkinsfile don't get cached, but that has the same `pip install .` that the CPU tests use. Effectively, we've just split it into two steps)
Additionally, this PR removes the `-e` flag from the CPU tests, since we should be testing the production install.
=> Make the installs for the GPU and CPU tests the same

jenkins/requirements.txt, plenoptic/synthesize/mad_competition.py, plenoptic/synthesize/metamer.py, plenoptic/synthesize/synthesis.py, tests/test_mad.py, tests/test_metamers.py
Our most recent test were failing, due to a problem with `dill`, which is a library that allows for pickling of more python callables. The most recent several versions of `dill` (at least `0.3.4` through `0.3.6`) give an error when loading a `Metamer` or `MADCompetition` object with the most recent version of `torch` (`1.13`). The error message was completely opaque to me (`AttributeError: Can't get attribute 'NoneType' on <module 'builtins' (built-in)>`) and I couldn't find any relevant info.
So, I'm removing `dill` as a requirement and switching back to using the built-in pickling. The reason I had added `dill` was to allow the pickling of arbitrary callables, but we've since limited what we expect (in particular, I used to allow `Metamer` to accept any callable as a model, but we've …
=> Remove dill

examples/Demo_Eigendistortion.ipynb, plenoptic/tools/data.py
This change fixes a recent issue with imageio that led to issues with:
1. Automatic conversion from floats in `[0,1]` to int8 images.
2. Changing what happens when `as_gray=False` and loading in a grayscale image.
Additionally, this adds support for RGBA images.
=> Imageio fix

README.md, docs/citation.rst, docs/conf.py, docs/index.rst, docs/install.rst, pyproject.toml
This PR:
- Adds citation guide
- Removes old tutorial badge (now, tutorials run as part of `build` action)
- Corrects `apidoc_module_dir` so modules are appropriately built in documentation
- Adds codecov badge to docs
- Fixes an issue with formatting on install instructions on index.rst
- Adds instructions for `ffmpeg` install
- Adds some useful sphinx extensions
=> Adds citation guide, minor improvements to docs

.readthedocs.yml, README.md
Readthedocs wasn't building from main because of an issue with pdf creation. Since that's not that useful, removing it.
Additionally, fixes link to citation guide in readme
=> Readthedocs hotfix

.github/workflows/ci.yml, CONTRIBUTING.md, docs/index.rst
- Rename "modules" to "API Documentation" in docs, which is more stanard
- Adds urlchecker action, to make sure all our urls are valid
=> Small documentation-related fixes

docs/install.rst
Very small PR to add info on minimum pip version number, following up on #227 .
Pip 21.3 is the minimum version at which they started supporting editable installs for `pyproject.toml`, see [changelog](https://pip.pypa.io/en/stable/news/#id286)
=> Adds info about pip minimum version

CONTRIBUTING.md, docs/conf.py, docs/index.rst, docs/install.rst, pyproject.toml
Adds some info to help explain optional dependencies and the branching workflow (@ericthomson I based a lot of that on what you have in Caiman, which is great!)
=> Updates installation instructions and CONTRIBUTING

src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py, src/plenoptic/simulate/models/naive.py, src/plenoptic/simulate/models/portilla_simoncelli.py, src/plenoptic/tools/validate.py, tests/conftest.py, tests/test_models.py, tests/test_steerable_pyr.py
With this PR, we make the models and canonical computations (everything in`plenoptic/simulate`) use `register_buffers`, which allows us to remove their `.to()` definitions and adds support for `.cpu()` and `.cuda()`. 
Note that this change *does not* affect the synthesis methods, because they're not modules. I may return to this at some point, but the rationale is because `torch.nn.Module` is the "base class for all neural network modules," as it says [in the docs](https://pytorch.org/docs/stable/generated/torch.nn.Module.html). Our models are similar enough that making them modules makes sense, but synthesis methods are fairly distinct (in particular, they don't necessarily involve optimization)
Closes #198
=> Switch models to using register_buffers

README.md, docs/citation.rst
Updates wording about "how to cite us"
Closes #240, #245
=> Citation update

.github/workflows/ci.yml
there are several cells in the notebooks whose output includes links that urlchecker think are invalid (though when I check them manually, they look fine). Regardless, they're unimportant -- they're part of warning messages and similar, so we don't want to check them.
=> Fix failing urlchecker by using `nbstripout`

tests/test_geodesic.py, tests/test_mad.py, tests/test_metamers.py
on other OSs, can get a different sample of uniform noise when setting the seed to 0, which means it doesn't always hit the stop criterion at the same time. however, it should still *hit* the stop criterion, so we just test against that directly
=> fix for test_stop_criterion

.github/workflows/ci.yml
This does two things:
- Updates action versions to get rid of the warning during github actions
- Changes how notebooks are tested: we were previously parallelizing across all of them, which I think was actually costing us time (and making it output to navigate), so now we run them all in one action.
=> Updates action versions, change how notebooks are tested

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ci.yml, .readthedocs.yml, CONTRIBUTING.md, README.md, docs/index.rst, jenkins/Dockerfile, jenkins/Jenkinsfile, pyproject.toml
With this, we update our supported python versions from 3.7-3.11 to 3.10-3.12, in order to be compliant with [SPEC0](https://scientific-python.org/specs/spec-0000/).
From now on, following that, we will support three python minor versions, rolling them over at the end of the year.
Closes #247
=> Updates python versions and trove classifiers

CITATION.cff, CONTRIBUTING.md, README.md, docs/conceptual_intro.rst, docs/conf.py, docs/index.rst, docs/install.rst, docs/make.bat, docs/models.rst, docs/reproducibility.rst, docs/scripts/conceptual_intro.py, docs/tips.rst, examples/02_Eigendistortions.ipynb, examples/README.md, pyproject.toml, src/plenoptic/metric/perceptual_distance.py, src/plenoptic/simulate/models/frontend.py, src/plenoptic/simulate/models/portilla_simoncelli.py, src/plenoptic/synthesize/eigendistortion.py, src/plenoptic/synthesize/geodesic.py, src/plenoptic/synthesize/mad_competition.py, src/plenoptic/synthesize/metamer.py
Updates links from `LabForComputationalVision/plenoptic` to `plenoptic-org/plenoptic`
=> Updates github org name

jenkins/Jenkinsfile
Small fix to the jenkins job that runs when a PR is merged: need to add `-n 8`, because `-n auto` causes too many jobs to be run at once and thus CUDA to run out of memory. Had already done this for the jenkins jobs that run during a PR, but not the merge one.
=> Fix jenkins

pyproject.toml
Sphinx build is failing because of a change to docutils, which is discussed [here](https://github.com/CrossNox/m2r2/issues/68). By specifying the docutils version, this should solve the issue, but it should be only necessary temporarily until [nbsphinx-link makes the relevant update](https://github.com/vidartf/nbsphinx-link/pull/23)
=> Specify docutils version

docs/models.rst, src/plenoptic/metric/perceptual_distance.py, src/plenoptic/synthesize/eigendistortion.py, src/plenoptic/synthesize/mad_competition.py, src/plenoptic/synthesize/metamer.py, src/plenoptic/synthesize/synthesis.py, src/plenoptic/tools/conv.py, src/plenoptic/tools/signal.py, src/plenoptic/tools/validate.py, tests/conftest.py, tests/test_eigendistortion.py, tests/test_mad.py, tests/test_metamers.py, tests/test_tools.py
As documented in #283, calling `.synthesize()` after `.to()` raises a `ValueError` because `met.metamer` was no longer a leaf tensor. This is because, for some reason, `Tensor.to` is considered a differentiable operation. I'm not sure why that's desirable behavior, but this PR adds a solution: when moving tensors, we call `tensor.data.to` (instead of `tensor.to`) and then check whether the original version required a gradient and, if so, add it back. This is similar to how we behave in `load`. 
You can find some discussions of this issue: [on the pytorch forum](https://discuss.pytorch.org/t/moving-tensors-between-devices/83261/3), and on stackoverflow ([one](https://stackoverflow.com/questions/63662624/how-do-i-retain-grads-and-also-change-device-type-in-pytorch), …
=> Fix broken to method, test non-standard models/metrics, don't assume dtype

.github/workflows/ci.yml
Small change to fix failing urlchecker action: we can't make changes to the default python env, but pipx is available by default, so use that to install nbstripout
=> pip -> pipx install nbstripout

docs/conf.py
Removes duplicate `exclude_patterns` from conf.py, since that means the first one was getting ignored.
Closes #299
=> Remove duplicate `exclude_patterns`

src/plenoptic/tools/data.py, tests/test_tools.py
This small PR allows the user to specify the direction of the polar angle in the polar_angle synthetic image. By default, it increases clockwise, which matches the previous behavior (and documentation). However, the standard convention is to have the angle increase counter-clockwise, which this then allows the user to do.
Also removes an unnecessary deprecated decorator.
=> Allows user to specify polar_angle direction

src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py, src/plenoptic/tools/display.py, tests/test_steerable_pyr.py
An update in the ruff version caused more tests to fail. As part of that update, realized we weren't testing the steerable pyramid initialization with an invalid height value, so added that as well. The height must now be non-negative, and height=0 just returns the residuals.
=> Fix failing ruff check, adds check for steerpyr height

jenkins/Dockerfile, jenkins/Jenkinsfile
Adds the Jenkins job that builds the documentation and pushes to [separate repo](https://github.com/plenoptic-org/plenoptic-documentation).
The development of this has occurred elsewhere: [jenkins-webserver-template](https://github.com/flatironinstitute/jenkins-webserver-template) and [plenoptic-workshops](https://github.com/plenoptic-org/plenoptic-workshops) / [plenoptic-cshl-vision-2024](https://github.com/plenoptic-org/plenoptic-cshl-vision-2024)
=> Jenkins docs

jenkins/Jenkinsfile, tests/test_tools.py
By default, our Jenkins set up doesn't grab git tags, but we need them in order to properly version plenoptic when it's installed before building the docs (since sphinx includes the version in the output). This makes sure to fetch them before installing plenoptic in the docs build.
=> adds git fetch --tags

.gitignore, docs/conf.py, pyproject.toml, src/plenoptic/__init__.py
While putting together PRs for nemos and pynapple to use `setuptools_scm` to set the package version dynamically, realized that setuptools_scm doesn't recommend writing version to file anymore but using `importlib.metadata` ([docs](https://setuptools-scm.readthedocs.io/en/latest/usage/), in line with [PEP 566](https://peps.python.org/pep-0566/).
This similarly updates how sphinx grabs the version, in line with their suggestions as well.
=> Update how dynamic version is set

src/plenoptic/metric/classes.py, src/plenoptic/metric/perceptual_distance.py
Adds brief description for where the NLPD parameters came from (the matlab code for the [paper](https://library.imaging.org/ei/articles/28/16/art00008), found on the [lab website](https://www.cns.nyu.edu/~lcv/NLPyr/NLP_dist.m)).
As of right now, that link is down, so we grabbed them from the [internet archive](https://web.archive.org/web/20190522203913/https://www.cns.nyu.edu/~lcv/NLPyr/NLP_dist.m).
=> Document where nlpd parameters came from

src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py, tests/test_steerable_pyr.py
The error message when the steerable pyramid was passed an input with the wrong shape was confusing, hopefully this makes it clearer.
Also adds validation and casting for steerpyr's image shape: image shape must be an iterable of length two whose values are castable to ints.
=> Updates steerable pyramid error message on shape mismatch

CONTRIBUTING.md, noxfile.py
Makes sure CONTRIBUTING is up to date with what we're doing. Also updates noxfile:
- remove coverage session (coverage happens as part of tests, using pytest-coverage)
- adds ruff format session, as well as ruff check
- makes sure nox uses the same ruff version as pre-commit (this requires additionally installing pyyaml, but I think it's worth it).
=> updates CONTRIBUTING and noxfile

.github/ISSUE_TEMPLATE/bug_report.md, src/plenoptic/simulate/canonical_computations/filters.py, src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py, src/plenoptic/tools/data.py, src/plenoptic/tools/external.py
Fix two deprecation warnings:
- imageio API change. I believe this change doesn't affect me (after looking through [their migration guide](https://imageio.readthedocs.io/en/stable/reference/userapi.html#migrating-to-the-v3-api)), so this just explicitly imports `imageio.v3` to suppress the warning.
- torch.meshgrid change, see [docs](https://pytorch.org/docs/stable/generated/torch.meshgrid.html), [issue](https://github.com/pytorch/pytorch/issues/50276). torch's meshgrid default behavior was backwards from that of numpy. they are planning on changing default behavior to match that of numpy. now, I explicitly set indexing arg for all calls to either numpy or torch meshgrid. I had ran into this at one point when creating the `polar_radius` / `polar_angle` functions and had a comment to the …
=> Fix deprecation warnings

src/plenoptic/simulate/canonical_computations/filters.py, src/plenoptic/simulate/models/frontend.py, src/plenoptic/simulate/models/naive.py, src/plenoptic/tools/signal.py, src/plenoptic/tools/validate.py, tests/test_models.py, tests/test_tools.py
This PR makes several small quality-of-life changes:
- Makes center_crop better behaved. We now validate the input args and raise informative ValueErrors if e.g., you want to crop the center 200 pixels of a 100x100 image
- finishes adding type-hinting and doctests to models/naive.py and models/frontend.py
- better validation of inputs to `circular_gaussian2d`, raising more informative error messages when things go wrong
=> Improvements to center_crop, simple models

.pre-commit-config.yaml, docs/conceptual_intro.md, src/plenoptic/tools/display.py, tests/check_sphinx_directives.py
I add a couple of `..plot::`, which don't render correctly. They should look like `.. plot::` (note the space).
This fixes that and then adds a small script with accompanying pre-commit hook which checks for anything that matches the regex `\.\.[a-z]+::` and raises an error if so. Hopefully this will catch that in the future. The script is intended to run on only python, markdown, and rST; that constraint is handled by pre-commit.
=> Fix malformed sphinx directives

src/plenoptic/synthesize/eigendistortion.py, src/plenoptic/synthesize/mad_competition.py, src/plenoptic/synthesize/metamer.py, src/plenoptic/synthesize/synthesis.py, tests/test_eigendistortion.py, tests/test_mad.py, tests/test_metamers.py
Issue with calling `eigendistortion.to` with the frontend models (and similar).
updates `test_to` to check for this, and updates metamer tests to make sure we similarly check for it.
Additionally, allow user to set atol/rtol used when checking tensor equality during load. When trying to save/load on two machines, you can end up with very small differences that are not easily resolvable. (I ran into this on my work laptop and linux workstation, which both had the same versions of plenoptic and torch, and the problem didn't depend on GPU vs CPU; my guess is that it was something related to CUDA or BLAS). For example:
```python
img = po.data.einstein()
model = po.simul.CenterSurround(31, cache_filt=True, pad_mode='circular')
eig = po.synth.Eigendistortion(img, model)
eig.synthesize(5) …
```
=> Hotfix: fix eigendistortion.to()

src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py
@Bichidian noticed that they were swapped.
The real-valued is odd symmetric (like sine), the imaginary-valued is even symmetric (like cosine).
=> corrects even/odd in steerpyr docstring

docs/conf.py, pyproject.toml, src/plenoptic/metric/classes.py, src/plenoptic/metric/perceptual_distance.py, src/plenoptic/simulate/canonical_computations/non_linearities.py, src/plenoptic/simulate/canonical_computations/steerable_pyramid_freq.py, src/plenoptic/simulate/models/frontend.py, src/plenoptic/simulate/models/naive.py, src/plenoptic/simulate/models/portilla_simoncelli.py, src/plenoptic/synthesize/autodiff.py, src/plenoptic/synthesize/eigendistortion.py, src/plenoptic/synthesize/mad_competition.py, src/plenoptic/synthesize/metamer.py, src/plenoptic/tools/__init__.py, src/plenoptic/tools/conv.py, src/plenoptic/tools/convergence.py, src/plenoptic/tools/data.py, src/plenoptic/tools/display.py, src/plenoptic/tools/external.py, src/plenoptic/tools/io.py, src/plenoptic/tools/optim.py, src/plenoptic/tools/signal.py, src/plenoptic/tools/stats.py, src/plenoptic/tools/validate.py, tests/check_docstrings.py, tests/test_display.py, tests/test_metamers.py, tests/test_steerable_pyr.py, tests/test_tools.py, tests/utils.py
This PR continues the work started in #349: now all docstrings should pass validation.
This also:
- adds proper cross-references to pyrtools
- corrects the steer pyr docstring (#351 wasn't right, the parity of the filter depends on the order of the pyramid)
- adds some more validation to check for missed cross-references or None/False/True that should be wrapped in double backticks
- `animshow` now supports `zoom=None`, just like `imshow`.
- adds tests for `animshow` / `imshow` `zoom` arg.
=> More docstrings!
